version: '2'

services:
  identity-app:
   image: dockerhub.fokus.fraunhofer.de:5000/blockchain/identity-app
   container_name: identity-app
   ports:
     - 8080:8001
   environment:
     - ETHEREUM_ADDRESS=http://localhost:8545
     - FAUCET_ADDRESS=http://localhost:4000
     - SECRET_SHARING_SERVICE=http://localhost:5000
   depends_on:
     - identity-faucet
     - testrpc_server
     - secret_sharing_service

  identity-faucet:
   image: dockerhub.fokus.fraunhofer.de:5000/blockchain/identity-faucet
   container_name: identity-faucet
   ports:
     - 4000:4000
   environment:
     - PORT=4000
     - ETHEREUM_ADDRESS=http://testrpc_server:8545
     - FUEL_SERVICE=http://ether-fuel-service:6000
     - IPFS_NODE_HOST=ipfs_server
     - IPFS_NODE_PORT=5002
   depends_on:
     - testrpc_server
     - ether-fuel-service
     - ipfs_server
   links:
     - testrpc_server:testrpc_server
     - ether-fuel-service:ether-fuel-service
     - ipfs_server:ipfs_server

  ether-fuel-service:
   image: dockerhub.fokus.fraunhofer.de:5000/blockchain/ether-fuel-service
   container_name: ether-fuel-service
   ports:
     - 6000:6000
   environment:
     - PORT=6000
     - ETHEREUM_ADDRESS=http://testrpc_server:8545
     - SEED_PHRASE=route harbor drastic pigeon asset circle vintage robust catalog vendor okay vault
     - GAS_LIMIT=6721975
     - GAS_PRICE=20000000000
     - AMOUNT=650000000000000000
     - NO_OF_ADDRESSES=10
   depends_on:
     - testrpc_server
   links:
     - testrpc_server:testrpc_server

  testrpc_server:
    image: dockerhub.fokus.fraunhofer.de:5000/blockchain/testrpc_network
    container_name: testrpc_server
    ports:
      - 8545:8545
  
  ipfs_server:
    image: dockerhub.fokus.fraunhofer.de:5000/blockchain/ipfs_network
    container_name: ipfs_server
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
      - 8081:8081
  
  secret_sharing_service:
    image: dockerhub.fokus.fraunhofer.de:5000/secret_sharing/api_service
    ports:
     - 5000:5000